# Generated by Django 3.1.3 on 2020-11-15 00:01

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('cor', models.CharField(max_length=8)),
                ('castrado', models.BooleanField()),
                ('tipo', models.CharField(choices=[('CÃO', 'Cão'), ('GATO', 'Gato')], max_length=4)),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to='./images', verbose_name='Imagem')),
            ],
        ),
    ]
