# Generated by Django 3.1.3 on 2020-11-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animal_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='autor',
            new_name='usuario',
        ),
    ]
