# Generated by Django 3.1.3 on 2020-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201123_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='usuario_novo',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
