# Generated by Django 3.1.3 on 2020-12-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_animal_usuario_novo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='usuario_novo',
        ),
    ]
