# Generated by Django 3.1.3 on 2020-12-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201205_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Cidade',
            field=models.CharField(default='Recife', max_length=30),
            preserve_default=False,
        ),
    ]
