# Generated by Django 3.1.4 on 2020-12-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_animal_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Cidade',
            new_name='cidade',
        ),
    ]
